language: ruby

rvm:
    - 2.1.3

env:
    - TASKWARRIOR=v2.4.1

before_install:
    - sudo apt-get install -y python-dev cmake build-essential libgnutls28-dev uuid-dev gnutls-bin chrpath libssl-dev libfontconfig1-dev    - git clone https://git.tasktools.org/scm/tm/task.git
    - cd task
    - git checkout $TASKWARRIOR
    - cmake .
    - make
    - sudo make install
    - task --version
    - cd ../

script: 'bundle exec rake'

notifications:
    email: false
